# Import Libraries

In [2]:
import os
import sys
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import PIL
import torch
import torchvision
from PIL import Image
from torchvision import transforms
import numpy as np

## Check library versions

In [4]:
print("System platform: ", sys.platform)
print("System version: ", sys.version)
print("matplotlib version: ", matplotlib.__version__)
print("pandas version: ", pd.__version__)
print("PIL version: ", PIL.__version__)
print("torch version: ", torch.__version__)
print("torchvision version: ", torchvision.__version__)

System platform:  win32
System version:  3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
matplotlib version:  3.10.7
pandas version:  2.3.3
PIL version:  12.0.0
torch version:  2.9.1+cpu
torchvision version:  0.24.1+cpu


## get a link path to the data

In [6]:
# create a path that leads directly to the data files
data = os.path.join("C:\\Users\\User\\Downloads\\EuroSAT_RGB", "C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB")
data

'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB'

## TO get a list of all the classes in the dataset

In [8]:
listOfClasses = os.listdir(data)
print(f"The number of classes is {len(listOfClasses)}")
print(f"The type of class is {type(listOfClasses)}")
listOfClasses

The number of classes is 10
The type of class is <class 'list'>


['AnnualCrop',
 'Forest',
 'HerbaceousVegetation',
 'Highway',
 'Industrial',
 'Pasture',
 'PermanentCrop',
 'Residential',
 'River',
 'SeaLake']

## check the number of images in each classes

In [10]:
# so first we create a link to each class, then we count the number of images in each class
data_pasture = os.path.join(data, "C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Pasture")
data_pasture

'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Pasture'

In [11]:
data_permanentcrop = os.path.join(data, "C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\PermanentCrop")
data_permanentcrop

'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\PermanentCrop'

In [12]:
data_residential = os.path.join(data, "C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Residential")
data_residential

'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Residential'

In [13]:
data_industrial = os.path.join(data, "C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Industrial")
data_industrial

'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Industrial'

In [14]:
data_herbaceousVegetation = os.path.join(data, "C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\HerbaceousVegetation")
data_herbaceousVegetation

'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\HerbaceousVegetation'

In [15]:
data_sealake = os.path.join(data, "C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\SeaLake")
data_sealake

'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\SeaLake'

In [16]:
data_annualcrop = os.path.join(data, "C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\AnnualCrop")
data_annualcrop

'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\AnnualCrop'

In [17]:
data_highway = os.path.join(data, "C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Highway")
data_highway

'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Highway'

In [18]:
data_river = os.path.join(data, "C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\River")
data_river

'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\River'

In [19]:
data_forest = os.path.join(data, "C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Forest")
data_forest

'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Forest'

## so now we check whether they have same nukber of images in all the classes

In [21]:
# so now we check the length of all the classes in the dataset
print("No of Pasture Images: ", len(os.listdir(data_pasture)))
print("No of permanent crop Images: ", len(os.listdir(data_permanentcrop)))
print("No of residential Images: ", len(os.listdir(data_residential)))
print("No of industrial Images: ", len(os.listdir(data_industrial)))
print("No of herbaceousVegetation Images: ", len(os.listdir(data_herbaceousVegetation)))
print("No of sealake Images: ", len(os.listdir(data_sealake)))
print("No of annualcrop Images: ", len(os.listdir(data_annualcrop)))
print("No of highway Images: ", len(os.listdir(data_highway)))
print("No of river Images: ", len(os.listdir(data_river)))
print("No of forest Images: ", len(os.listdir(data_forest)))

No of Pasture Images:  2000
No of permanent crop Images:  2500
No of residential Images:  3000
No of industrial Images:  2500
No of herbaceousVegetation Images:  3000
No of sealake Images:  3000
No of annualcrop Images:  3000
No of highway Images:  2500
No of river Images:  2500
No of forest Images:  3000


## Now time to split the data into train, validate and test.

### First we create a list with all the images

In [24]:
# we use stratified splitting here, because the number of images in each class is not the same.
# to do this we first create empty lists of images and labels
image_list = []
labels_list = []

# create a list with all the links of all the classes
classes = [data_pasture, data_permanentcrop, data_residential, data_industrial, data_herbaceousVegetation, data_sealake, data_annualcrop, data_highway, data_river, data_forest]

# now use a for loop to append all the images and their respective lasses into the list of mages and labels
for k in classes:
    for img in os.listdir(k):
        image_list.append(os.path.join(k, img))
        labels_list.append(k)


# print the number of images altogether
print(f"The number of images altogether is {len(image_list)}")

The number of images altogether is 27000


### now we use stratified splitting to finish the rest

In [26]:
from sklearn.model_selection import train_test_split

# now remove the train data from the rest
x_train, x_rem, y_train, y_rem = train_test_split(image_list, labels_list, test_size = 0.30, stratify = labels_list, random_state = 42)

# now remove seperate the test and validate data
x_val, x_test, y_val, y_test = train_test_split(x_rem, y_rem, test_size = 0.50, stratify = y_rem, random_state = 26)

# now let's check the shape of the train, validate and tests datasets
len(x_train), len(x_val), len(x_test), len(y_train), len(y_val), len(y_test)

(18900, 4050, 4050, 18900, 4050, 4050)

## Use ResNet to reduce dimensions of the images to fit size for QNN

### Load images and convert to Tensor

#### Define the transformer first

In [30]:
# before we load are images using ImageFolder, we have to define our transformer first
transform = transforms.Compose(
    [
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(
            mean = [0.485, 0.456, 0.406],
            std = [0.229, 0.224, 0.225]
        )
    ]
)

#### import some extra libraries

In [32]:
# import some extra libraries
from torchvision.datasets import ImageFolder
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from PIL import Image

#### Create a class that does the conversion of images to actual tensors.

In [34]:
# now create a class (Dataset) that does the conversion of our images to actual tensors
class ImagePathDataset(Dataset):
    # so we want our class to take in the list of image paths, the list of labels and the transform function we have defined
    def __init__(self, paths, labels, transform):
        self.paths = paths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        # here we would like to know the number of images
        return len(self.paths)

    def __getitem__(self, i):
        # now we open each image and convert it to RGB and apply our transforms, then we return the image and the label
        img = Image.open(self.paths[i]).convert("RGB")
        img = self.transform(img)
        return img, self.labels[i]

#### Now convert the y_train into a list of encoded class id's

In [36]:
# create a class of all the unique elements in the y_train tuple
classes = sorted(set(y_train))

# create a dictionary of class and class id using dictionary comprehension and the list of classes we defined earlier
classIdDict = {cls: i for i, cls in enumerate(classes)}
classIdDict

{'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\AnnualCrop': 0,
 'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Forest': 1,
 'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\HerbaceousVegetation': 2,
 'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Highway': 3,
 'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Industrial': 4,
 'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Pasture': 5,
 'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\PermanentCrop': 6,
 'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\Residential': 7,
 'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\River': 8,
 'C:\\Users\\User\\Downloads\\EuroSAT_RGB\\EuroSAT_RGB\\SeaLake': 9}

In [37]:
# now we convert the class paths to id's in y_train using list comprehension
y_train = [classIdDict[y] for y in y_train]
y_val = [classIdDict[y] for y in y_val]
y_test = [classIdDict[y] for y in y_test]

#### Now convert the images to tensrs

In [39]:
train_ds = ImagePathDataset(x_train, y_train, transform)
val_ds   = ImagePathDataset(x_val, y_val, transform)
test_ds  = ImagePathDataset(x_test, y_test, transform)

train_loader = DataLoader(train_ds, batch_size=16, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=16, shuffle=False)
test_loader = DataLoader(test_ds, batch_size=16, shuffle=False)

### Confirm whether it is a tensor

In [41]:
images, labels = next(iter(train_loader))

# check the type
print(type(images))
print(type(labels))

# check the shape
print(images.shape)
print(labels.shape)

<class 'torch.Tensor'>
<class 'torch.Tensor'>
torch.Size([16, 3, 224, 224])
torch.Size([16])


### Import and load Resnet and remove the classification layer

In [43]:
import os
os.makedirs(r"C:\Users\User\.cache\torch\hub\checkpoints", exist_ok=True)

In [44]:
# import the required libraries
import torchvision.models as models
import torch.nn as nn

# everything runs on CPU
device = torch.device("cpu")

# load pretrained Resnet model - ResNet18
resnet = models.resnet18(pretrained = True)

# remove the final classification layer
# we list all the layers of resnet, then we remove the last fuly connected layer
resnet = nn.Sequential(*list(resnet.children()) [:-1])

# set model to evaluation mode
resnet.eval()

C:\Users\User\shap311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\User\shap311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Sequential(
  (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU(inplace=True)
  (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (4): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Con

### Extract the features once using Resnet

In [46]:
# we create a list to store the features and labels
features = []
labels = []

# we need to let pytorch know that we are training resnet, but using it as an extraction function
with torch.no_grad():
    for imgs, lbls in train_loader:
        # for the images and labels in our dataloader, we want resnet to extract the features
        out = resnet(imgs)
        # now we resize the tensor output, so the result is clear
        out = out.view(out.size(0), -1)
        # append the results to the list we created
        features.append(out)
        labels.append(lbls)

# so now we store the features of the extraction
x_train_feat = torch.cat(features)
y_train_feat = torch.cat(labels)

In [47]:
# now check the type and shape of the new x and y train
print(type(x_train_feat))
print(type(y_train_feat))

print(x_train_feat.shape)
print(y_train_feat.shape)

<class 'torch.Tensor'>
<class 'torch.Tensor'>
torch.Size([18900, 512])
torch.Size([18900])


In [48]:
# now save the features extracted 
torch.save(x_train_feat, "X_train_resnet.pt")
torch.save(y_train_feat, "y_train.pt")

In [49]:
# lets do the same thing for validation and test data
# validation data now
features_val = []
labels_val = []

# now to using resnet as a feature extraction function
with torch.no_grad():
    for val_im, val_ls in val_loader:
        # using for loop to loop through all the images and labels in our dataloader and extract the features with resnet
        out_val = resnet(val_im)
        out_val = out_val.view(out_val.size(0), -1)
        # now append results to the features and labels list
        features_val.append(out_val)
        labels_val.append(val_ls)

# store th features of the extraction
x_val_feat = torch.cat(features_val)
y_val_feat = torch.cat(labels_val)

In [50]:
# now check the type and shape of the new x and y train
print(type(x_val_feat))
print(type(y_val_feat))

print(x_val_feat.shape)
print(y_val_feat.shape)

<class 'torch.Tensor'>
<class 'torch.Tensor'>
torch.Size([4050, 512])
torch.Size([4050])


In [51]:
# lets do the same thing for test data
# validation data now
features_test = []
labels_test = []

# now to using resnet as a feature extraction function
with torch.no_grad():
    for test_im, test_ls in test_loader:
        # using for loop to loop through all the images and labels in our dataloader and extract the features with resnet
        out_test = resnet(test_im)
        out_test = out_test.view(out_test.size(0), -1)
        # now append results to the features and labels list
        features_test.append(out_test)
        labels_test.append(test_ls)

# store th features of the extraction
x_test_feat = torch.cat(features_test)
y_test_feat = torch.cat(labels_test)

In [52]:
# now check the type and shape of the new x and y train
print(type(x_test_feat))
print(type(y_test_feat))

print(x_test_feat.shape)
print(y_test_feat.shape)

<class 'torch.Tensor'>
<class 'torch.Tensor'>
torch.Size([4050, 512])
torch.Size([4050])


In [53]:
# now save the features extracted for val
torch.save(x_val_feat, "x_val_resnet.pt")
torch.save(y_val_feat, "y_val.pt")
# now save the features extracted for test
torch.save(x_test_feat, "x_test_resnet.pt")
torch.save(y_test_feat, "y_test.pt")

## Standard Scale the output of the resnet model

In [55]:
# to do this we convert our data in tensor form to numpy form
x_train_np = x_train_feat.numpy()

# now print the type, size and number of dimensions of the new x_train
print(x_train_np.dtype)
print(x_train_np.size)
print(x_train_np.ndim)
print(x_train_np.shape)

float32
9676800
2
(18900, 512)


In [56]:
# now we use the pca to transform the validate and test data
# but first we convert the data to numpy first
x_val_np = x_val_feat.numpy()
x_test_np = x_test_feat.numpy()

In [57]:
# now we scale the train data using our standard scaler
from sklearn.preprocessing import StandardScaler

# define our scalar fuction
ss = StandardScaler()
ss

,copy,True
,with_mean,True
,with_std,True


In [58]:
x_train_ss = ss.fit_transform(x_train_np)
x_train_ss

array([[-0.8478692 , -0.8248117 , -0.75696707, ..., -0.85933816,
        -0.58690447, -0.65864104],
       [-0.40793175,  1.2302884 ,  0.9094445 , ...,  1.201784  ,
        -0.5945957 , -0.65864104],
       [-0.60631436, -0.8248117 , -0.71428394, ..., -1.0974472 ,
        -0.50894696, -0.6406419 ],
       ...,
       [ 2.5492728 ,  0.7707304 , -0.7363094 , ..., -0.42244947,
         0.8252451 ,  0.8344655 ],
       [ 2.5673068 , -0.21590374, -0.39947248, ...,  0.9995103 ,
        -0.61996734,  4.095565  ],
       [-0.33981898, -0.5914624 , -0.7371467 , ..., -0.83689386,
        -0.75897664, -0.05840386]], shape=(18900, 512), dtype=float32)

In [59]:
# now we standard scale the test and validate data
x_val_ss = ss.transform(x_val_np)
x_test_ss = ss.transform(x_test_np)

# Quantum Satellite Monitoring Assistant

First to o this, we first use pca, to extract the features to the form we need suitable for our QNN model to take in the features of the images.

## PCA Analysis of the extracted features

### Extract 8, 16 and 20 PCA features for each of the QSMA i am going to build

In [64]:
# import the pca library from sklearn
from sklearn.decomposition import PCA
pca = PCA(n_components = 8)
pca_16 = PCA(n_components = 16)
pca_20 = PCA(n_components = 20)
pca

,n_components,8
,copy,True
,whiten,False
,svd_solver,'auto'
,tol,0.0
,iterated_power,'auto'
,n_oversamples,10
,power_iteration_normalizer,'auto'
,random_state,None


#### Extract the 8 image features using pca for train, test and validation

In [66]:
# use pca to train transform the training data and the validate and test data
x_train_pca = pca.fit_transform(x_train_ss)
x_train_pca

array([[-13.039432  ,   2.7585344 ,  -3.1836553 , ...,   1.740369  ,
         -0.1624617 ,  -1.293453  ],
       [  0.55611163,   0.02592521,  -0.9021121 , ...,   2.1660652 ,
          1.8700987 ,   2.2891116 ],
       [-14.826339  ,   0.8968484 ,  -3.5781815 , ...,   6.9886885 ,
         -2.3519797 ,   2.0887687 ],
       ...,
       [  1.3620933 ,   6.15853   ,   3.772924  , ...,  -0.96060807,
         -0.43075234,   8.108901  ],
       [ 15.330181  ,   7.985897  ,   4.5052547 , ...,  -0.5021075 ,
         -1.7963444 ,  -1.8214061 ],
       [ -0.32916752,  -7.673485  ,   4.8784237 , ...,  -2.5240006 ,
         -3.5471427 ,  -1.7632105 ]], shape=(18900, 8), dtype=float32)

In [67]:
# now we transform them
x_val_pca = pca.transform(x_val_ss)
x_test_pca = pca.transform(x_test_ss)

#### checking the importance of the 8 pca features i just extracted

In [69]:
# lets check how important each feature created by pca is
pca.explained_variance_ratio_

array([0.18391007, 0.05075788, 0.04320071, 0.04216721, 0.02677374,
       0.02237053, 0.01977221, 0.01660084], dtype=float32)

In [70]:
np.cumsum(pca.explained_variance_ratio_)

array([0.18391007, 0.23466796, 0.27786866, 0.32003587, 0.34680963,
       0.36918017, 0.38895237, 0.40555322], dtype=float32)

#### Extract 16 of the features from each of the images using pca

In [72]:
# use pca_16 to train transform the training data and the validate and test data
x_train_pca_16 = pca_16.fit_transform(x_train_ss)
x_train_pca_16

array([[-1.3039434e+01,  2.7585349e+00, -3.1836557e+00, ...,
        -2.2216415e+00, -2.4175903e-01, -4.5632743e-03],
       [ 5.5611110e-01,  2.5925450e-02, -9.0211177e-01, ...,
         2.5513442e+00, -1.2362113e+00,  2.1343052e-01],
       [-1.4826343e+01,  8.9684802e-01, -3.5781815e+00, ...,
         2.8758276e-01, -3.3776253e-01,  1.1529812e-01],
       ...,
       [ 1.3620933e+00,  6.1585302e+00,  3.7729239e+00, ...,
        -5.7169590e+00,  4.7002628e-01, -5.7391810e-01],
       [ 1.5330181e+01,  7.9858971e+00,  4.5052547e+00, ...,
         2.8577760e-01, -1.6978703e+00,  3.6340828e+00],
       [-3.2916752e-01, -7.6734848e+00,  4.8784237e+00, ...,
        -4.1093979e+00,  1.2879314e-01,  6.0383183e-01]],
      shape=(18900, 16), dtype=float32)

In [73]:
# now we transform the val and test
x_val_pca_16 = pca_16.transform(x_val_ss)
x_test_pca_16 = pca_16.transform(x_test_ss)

#### So how important are these 16 features, do they tell us a lot about the images

In [75]:
# lets check how important each feature created by pca_16 is
pca_16.explained_variance_ratio_

array([0.18391007, 0.05075788, 0.04320071, 0.04216721, 0.02677374,
       0.02237053, 0.01977221, 0.01660084, 0.01565346, 0.01455977,
       0.01378861, 0.013109  , 0.01115091, 0.0108982 , 0.00991528,
       0.00896766], dtype=float32)

In [76]:
np.cumsum(pca_16.explained_variance_ratio_)

array([0.18391007, 0.23466796, 0.27786866, 0.32003587, 0.34680963,
       0.36918017, 0.38895237, 0.40555322, 0.42120668, 0.43576646,
       0.44955507, 0.46266407, 0.47381496, 0.48471317, 0.49462843,
       0.50359607], dtype=float32)

So the 16 features pca extraction tells us slightly above 50% of the images we have here will this be good for our classification, and remember we will compare our results othe claical counter part. 

#### Extract 20 features from the image using pca

In [79]:
x_train_pca_20 = pca_20.fit_transform(x_train_ss)
x_train_pca_20

array([[-13.039434  ,   2.758535  ,  -3.1836557 , ...,   1.0119288 ,
         -0.26849616,   0.54937834],
       [  0.5561111 ,   0.02592545,  -0.90211177, ...,  -0.13242128,
          1.3471167 ,   2.5927467 ],
       [-14.826343  ,   0.896848  ,  -3.5781815 , ...,  -0.9044914 ,
         -1.0484444 ,   0.2529248 ],
       ...,
       [  1.3620933 ,   6.15853   ,   3.772924  , ...,   0.9307631 ,
          0.17496727,  -1.6998211 ],
       [ 15.330181  ,   7.985897  ,   4.5052547 , ...,  -5.1759806 ,
         -0.1215405 ,  -1.9650611 ],
       [ -0.32916752,  -7.673485  ,   4.8784237 , ...,  -2.9730215 ,
         -1.3982351 ,  -2.3393514 ]], shape=(18900, 20), dtype=float32)

In [80]:
# now we transform the validation and the test data
x_val_pca_20 = pca_20.transform(x_val_ss)
x_test_pca_20 = pca_20.transform(x_test_ss)

#### So how important are the 20 features extracted using pca

In [82]:
# let's check the importance of the features extracted using pca_20
pca_20.explained_variance_ratio_

array([0.18391007, 0.05075788, 0.04320071, 0.04216721, 0.02677374,
       0.02237053, 0.01977221, 0.01660084, 0.01565346, 0.01455977,
       0.01378861, 0.013109  , 0.01115091, 0.0108982 , 0.00991528,
       0.00896766, 0.00890506, 0.00845332, 0.00808193, 0.00786592],
      dtype=float32)

In [83]:
# checking the cumulative of all the explained variance for the pca_20
np.cumsum(pca_20.explained_variance_ratio_)

array([0.18391007, 0.23466796, 0.27786866, 0.32003587, 0.34680963,
       0.36918017, 0.38895237, 0.40555322, 0.42120668, 0.43576646,
       0.44955507, 0.46266407, 0.47381496, 0.48471317, 0.49462843,
       0.50359607, 0.5125011 , 0.52095443, 0.52903634, 0.53690225],
      dtype=float32)

## Angle Encoding of the data

### Angle normalisation of the data

#### Create a function to angle normalise the data

In [87]:
# we want to normalise our data over the angular range [-pi - pi], so since python has no defined function or class that can do this easily for us, we have to define the function for ourselves
class AngleNormalizer:
    # define the init method first
    def __init__(self):
        # so here we define the self parameter and the maximum variable per feature column
        self.max_abs_ = None
    def fit(self, X):
        # here we determine the absolute maximum value for each feature column
        self.max_abs_ = np.max(np.abs(X), axis = 0)
        # now just to make sure that we don't make mistake and get a zero maximum stored which can affect the model in the future
        # we assisgn every zero here to one
        self.max_abs_[self.max_abs_ == 0] = 1.0
        return self

    def transform(self, X):
        return np.pi * (X / self.max_abs_)

    def fit_transform(self, X):
        # in this method, we call th fit function on the data, store the maximum absolute values and return the normalised data from the trnsformed method
        self.fit(X)
        return self.transform(X)

#### Angle normalise the 8 features extracted by PCA

In [89]:
# so now we define a variiable that will be are angle normaliser
ang = AngleNormalizer()
ang

In [90]:
# next we fit transform the training data from pca with 8 features with
x_train_ang = ang.fit_transform(x_train_pca)
x_train_ang

array([[-1.2322655 ,  0.43034786, -0.56399643, ...,  0.4327347 ,
        -0.03737601, -0.2892067 ],
       [ 0.05255422,  0.00404449, -0.15981254, ...,  0.53858215,
         0.43023574,  0.5118288 ],
       [-1.4011337 ,  0.1399137 , -0.63388824, ...,  1.7377051 ,
        -0.5410975 ,  0.46703354],
       ...,
       [ 0.12872192,  0.96076745,  0.66838765, ..., -0.23885076,
        -0.09909908,  1.8130915 ],
       [ 1.4487482 ,  1.2458477 ,  0.7981228 , ..., -0.1248467 ,
        -0.41326782, -0.40725324],
       [-0.03110732, -1.1971095 ,  0.86423105, ..., -0.6275811 ,
        -0.8160572 , -0.39424106]], shape=(18900, 8), dtype=float32)

In [91]:
# now i need to transform the validation and test data
x_val_ang = ang.transform(x_val_pca)
x_test_ang = ang.transform(x_test_pca)

#### Angle normalise the 16 features extracted by PCA

In [93]:
# now let's do the same for the training, test and validation data of the pca with 16 features data
ang_16 = AngleNormalizer()

In [94]:
# next we fit transform the training data from pca with 16 features with
x_train_ang_16 = ang_16.fit_transform(x_train_pca_16)
x_train_ang_16

array([[-1.2322658e+00,  4.3034792e-01, -5.6399655e-01, ...,
        -3.8318920e-01, -5.9835974e-02, -1.1809078e-03],
       [ 5.2554175e-02,  4.0445249e-03, -1.5981248e-01, ...,
         4.4005635e-01, -3.0596542e-01,  5.5232655e-02],
       [-1.4011340e+00,  1.3991365e-01, -6.3388824e-01, ...,
         4.9602333e-02, -8.3597079e-02,  2.9837446e-02],
       ...,
       [ 1.2872192e-01,  9.6076745e-01,  6.6838765e-01, ...,
        -9.8606223e-01,  1.1633269e-01, -1.4852150e-01],
       [ 1.4487482e+00,  1.2458477e+00,  7.9812282e-01, ...,
         4.9290977e-02, -4.2022720e-01,  9.4044679e-01],
       [-3.1107321e-02, -1.1971095e+00,  8.6423105e-01, ...,
        -7.0878977e-01,  3.1876627e-02,  1.5626274e-01]],
      shape=(18900, 16), dtype=float32)

In [95]:
# now i need to transform the validation and test data
x_val_ang_16 = ang_16.transform(x_val_pca_16)
x_test_ang_16 = ang_16.transform(x_test_pca_16)

#### Angle normalise the 20 features extracted by PCA

In [97]:
# now let's do the same for the training, validation and test of the 20 features data extracted by PCA
ang_20 = AngleNormalizer()

In [98]:
# next we fit transform he training data from pca with 20 features 
x_train_ang_20 = ang_20.fit_transform(x_train_pca_20)
x_train_ang_20

array([[-1.2322658 ,  0.43034792, -0.56399655, ...,  0.25436023,
        -0.06704841,  0.13532569],
       [ 0.05255418,  0.00404452, -0.15981248, ..., -0.03328565,
         0.33639973,  0.63865864],
       [-1.401134  ,  0.13991365, -0.63388824, ..., -0.22735456,
        -0.2618158 ,  0.06230173],
       ...,
       [ 0.12872192,  0.96076745,  0.66838765, ...,  0.23395827,
         0.04369253, -0.41870865],
       [ 1.4487482 ,  1.2458477 ,  0.7981228 , ..., -1.3010436 ,
        -0.03035089, -0.48404393],
       [-0.03110732, -1.1971095 ,  0.86423105, ..., -0.74730396,
        -0.34916493, -0.576241  ]], shape=(18900, 20), dtype=float32)

In [99]:
# now we angle encode the validation and the test data
x_val_ang_20 = ang_20.transform(x_val_pca_20)
x_test_ang_20 = ang_20.transform(x_test_pca_20)

### CHeck where this code was runnning

In [101]:
import sys
sys.executable

'C:\\Users\\User\\shap311\\Scripts\\python.exe'

### Now we angle encode using pennylane

#### Angle encoding the 8 feature extracted data

In [104]:
# importing pennylane as we will be
import pennylane as qml

# okay now we get the number of qubits which is the number of features
n_qubits = x_train_ang.shape[1]

# create a quantum device with the number of qubits as the num ber of extracted pca features
dev = qml.device("default.qubit", wires = n_qubits)
dev

C:\Users\User\shap311\Lib\site-packages\pennylane\__init__.py:19: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


<DefaultQubit device (wires=8, shots=None) at 0x225add007d0>

In [105]:
# modify the function using a python decorator
@qml.qnode(dev)

# define a funcion to loop through each feature and angle encode
def angle_encoded_circuit(features):
    for i in range(len(features)):
        qml.RY(features[i], wires = i)

    # measure all qubits and return the values
    return [qml.expval(qml.PauliZ(i)) for i in range(len(features))]

In [106]:
# now we call our angle encoded function to encode our image features image by image
x_train_encoded = np.array(
    [
        angle_encoded_circuit(x) for x in x_train_ang
    ]
)
x_train_encoded

array([[ 0.33210169,  0.90882068,  0.8451255 , ...,  0.90782234,
         0.9993016 ,  0.95847042],
       [ 0.99861934,  0.99999182,  0.98725713, ...,  0.85843679,
         0.90886745,  0.87185028],
       [ 0.16884987,  0.99022804,  0.80573067, ..., -0.16613489,
         0.85714389,  0.89290783],
       ...,
       [ 0.99172677,  0.57289113,  0.78482189, ...,  0.97161051,
         0.9950937 , -0.2399314 ],
       [ 0.12174532,  0.3192601 ,  0.69805209, ...,  0.99221677,
         0.91581334,  0.91821225],
       [ 0.99951621,  0.36505033,  0.64922517, ...,  0.80945021,
         0.68509866,  0.92328834]], shape=(18900, 8))

In [107]:
# now let's angle encode the val and test datasets
x_val_encoded = np.array(
    [
        angle_encoded_circuit(x) for x in x_val_ang
    ]
)

x_test_encoded = np.array(
    [
        angle_encoded_circuit(x) for x in x_test_ang
    ]
)
x_val_encoded.shape, x_test_encoded.shape

((4050, 8), (4050, 8))

#### Angle encoding of 16 features extracted data of the images

In [109]:
# now we will also angle encode for the 16 features pca expansion data
# okay now we get the number of qubits which is the number of features
n_qubits_16 = x_train_ang_16.shape[1]

# create a quantum device with the number of qubits as the num ber of extracted pca features
dev_16 = qml.device("default.qubit", wires = n_qubits_16)
dev_16

<DefaultQubit device (wires=16, shots=None) at 0x225af4a1950>

In [110]:
# modify the function using a python decorator
@qml.qnode(dev_16)

# define a funcion to loop through each feature and angle encode
def angle_encoded_circuit(features):
    for i in range(len(features)):
        qml.RY(features[i], wires = i)

    # measure all qubits and return the values
    return [qml.expval(qml.PauliZ(i)) for i in range(len(features))]
    
# now we call our angle encoded function to encode our image features image by image
x_train_encoded_16 = np.array(
    [
        angle_encoded_circuit(x) for x in x_train_ang_16
    ]
)
x_train_encoded_16

array([[0.33210135, 0.90882066, 0.84512544, ..., 0.92747697, 0.99821036,
        0.9999993 ],
       [0.99861935, 0.99999182, 0.98725714, ..., 0.90472766, 0.9535566 ,
        0.99847506],
       [0.16884952, 0.99022804, 0.80573067, ..., 0.99877006, 0.9965078 ,
        0.9995549 ],
       ...,
       [0.99172677, 0.57289113, 0.78482189, ..., 0.55197768, 0.99324098,
        0.98899094],
       [0.12174532, 0.3192601 , 0.69805209, ..., 0.99878545, 0.91299627,
        0.58942715],
       [0.99951621, 0.36505033, 0.64922517, ..., 0.75915019, 0.99949198,
        0.9878158 ]], shape=(18900, 16))

In [111]:
# work on the validate and the test
x_val_encoded_16 = np.array(
    [
        angle_encoded_circuit(x) for x in x_val_ang_16
    ]
)

x_test_encoded_16 = np.array(
    [
        angle_encoded_circuit(x) for x in x_test_ang_16
    ]
)
x_val_encoded_16.shape, x_test_encoded_16.shape

((4050, 16), (4050, 16))

#### Angle Encoding of the 20 features extracted data of the images

In [113]:
# define the number of qubits and create a quantum device that will have 20 qubits where our QNN will be built
n_qubits_20 = x_train_ang_20.shape[1]

# now we create the quantum device
dev_20 = qml.device("default.qubit", wires = n_qubits_20)
dev_20

<DefaultQubit device (wires=20, shots=None) at 0x225b5fc8f90>

In [114]:
# modify the function using a python decorator
@qml.qnode(dev_20)

# define a function to loop through each feature and angle encode
def angle_encoded_circuit(features):
    for i in range(len(features)):
        qml.RY(features[i], wires = i)

    # measure all qubits and return the values
    return [qml.expval(qml.PauliZ(i)) for i in range(len(features))]

# Now we all call angle encoded functions to encode our image features image by image
x_train_encoded_20 = np.array(
    # now loop through the angle normalised 20 feature data and encode them using the function\
    [
        angle_encoded_circuit(x) for x in x_train_ang_20
    ]
)
x_train_encoded_20

array([[0.33210135, 0.90882066, 0.84512544, ..., 0.96782448, 0.9977531 ,
        0.99085744],
       [0.99861935, 0.99999182, 0.98725714, ..., 0.99944608, 0.9439492 ,
        0.80289609],
       [0.16884952, 0.99022804, 0.80573067, ..., 0.97426609, 0.96592158,
        0.99805987],
       ...,
       [0.99172677, 0.57289113, 0.78482189, ..., 0.97275637, 0.99904563,
        0.91361474],
       [0.12174532, 0.3192601 , 0.69805209, ..., 0.26649309, 0.99953945,
        0.88512027],
       [0.99951621, 0.36505033, 0.64922517, ..., 0.73352393, 0.93965873,
        0.83851675]], shape=(18900, 20))

In [115]:
# now let's do the same for the validation and the test data
x_val_encoded_20 = np.array(
    [
        angle_encoded_circuit(x) for x in x_val_ang_20
    ]
)

x_test_encoded_20 = np.array(
    [
        angle_encoded_circuit(x) for x in x_test_ang_20
    ]
)

## Let's build the Qnn circuit

In [117]:
# first we define the number of qubits in our QNN model
n_qubits = x_train_encoded.shape[1]
n_qubits

8

In [118]:
# so for this qnn we will use 2 layers for the training
n_layers = 2

In [119]:
# now we initialise trainable weights
weights = np.random.randn(n_layers, n_qubits, 3)
weights

array([[[-1.60301681, -0.74694837, -1.12713895],
        [ 0.01302905,  0.19274322, -0.61647988],
        [ 0.73202263,  1.46941867,  0.54098785],
        [-0.48808246, -1.45270017, -0.07663982],
        [ 1.15455164,  0.98219855, -2.56616771],
        [-0.230677  ,  1.52138551, -1.49751374],
        [-0.99655366, -0.5330455 , -0.38962834],
        [-0.8314359 , -0.28401203,  0.71554106]],

       [[-1.36031313, -0.16058146,  0.73670954],
        [ 0.27426487,  0.30972654,  1.71135925],
        [-0.95407047,  0.17922501,  1.30842228],
        [-1.98116142, -1.19554889, -0.95699515],
        [-0.91625363,  0.22234125, -0.17475723],
        [-0.59095586, -0.28513086, -0.1370507 ],
        [-0.59420686, -0.86244717,  0.74210715],
        [ 0.16250395, -0.86137703, -0.62495536]]])

### Define the QNN circuit

In [121]:
# define the decorator and use autograd interface differentiator
@qml.qnode(dev, interface = "autograd")

# now let's define the circuit
def qnn(features, weights):
    # encode data
    for i in range(n_qubits):
        qml.RY(features[i], wires = i)

    # now the two trainable layers will be built using for loops
    for k in range(weights.shape[0]):
        for i in range(n_qubits):
            qml.Rot(
                weights[1, i, 0],
                weights[1, i, 1],
                weights[1, i, 2],
                wires = i
            )
        # now we entangle the qubits that have learned from the pca features
        for i in range(n_qubits - 1):
            qml.CNOT(wires = [i, i + 1])

    # now the QNN circuit will return a result which is the pauli expected value for 10 classes
    return [
        qml.expval(qml.PauliZ(0)),
        qml.expval(qml.PauliZ(1)),
        qml.expval(qml.PauliZ(2)),
        qml.expval(qml.PauliZ(3))
    ]

### Label encoding 

In [123]:
# define a hot label encoding function
def one_hot(y, num_classes = 10):
    # create an array of zeros that will have this shape - the length of y ros and num of classes columns
    oh = np.zeros((len(y), num_classes))
    # now create an array of the lenght of y, and the next column should be the values of y then map it to 1
    oh[np.arange(len(y)), y] = 1
    return oh

### Define some crucial parameters and weights

In [125]:
# define the number of classes
n_classes = len(listOfClasses)

# now define the number of outputs from our qnn circuit function
n_quantum_outputs = 4

# now we define some classical weights and bias we will make use of in our loss function
w_classical = np.random.randn(n_quantum_outputs, n_classes)
b_classical = np.zeros(n_classes)

### Define the loss function

In [127]:
# here we define the loss function by calling our already defined qnn circuit and calating our prediction and the mean apsolute error of our prediction
# There is a numpy fnction we shall be using here which is pennylane's numpy for this work
import pennylane.numpy as pnp
def loss(weights, x, y):
    # create an array that stores the predictions of the qnn circuit from the train data
    predict = pnp.array([qnn(i, weights) for i in x])
    # now our results are in the form [-1, 1] we scale to the form [0, 1]
    predict = (predict + 1) / 2
    # so we defined the earlier weights because we want to be able to convert our 4 qnn outputs to classify our images among 10 classes
    # so we multiply our prediction by our classical weight then we add our bias
    logits = predict @ w_classical + b_classical
    # use softmax to create probabilities out of logits
    # to do that we first take the exponential of the logits subtracted from the largest logits
    exp_logits = pnp.exp(logits - pnp.max(logits, axis = 1, keepdims = True))
    # then we divide the exponential of the difference of each logits from the largest by the sum of them. THat is the probability
    probs = exp_logits / pnp.sum(exp_logits, axis = 1, keepdims = True)
    # using cross entropy to calculate our loss as we want to penalise the model for giving the right class a low probability
    # so we multiply out hot encoded labels to the log of the probability our model gave us
    return -pnp.mean(pnp.sum(y * pnp.log(probs + 1e-8), axis = 1))

### create our optimizer

In [129]:
opt = qml.AdamOptimizer(stepsize = 0.02)

### now straight to the training code asap

In [131]:
# before that we will just briefly convert our y train, test and val to numpy
y_train = np.array(y_train_feat)

C:\Users\User\AppData\Local\Temp\ipykernel_18324\3986826619.py:2: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  y_train = np.array(y_train_feat)


In [132]:
y_val = np.array(y_val_feat)
y_test = np.array(y_test_feat)

C:\Users\User\AppData\Local\Temp\ipykernel_18324\3220567389.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  y_val = np.array(y_val_feat)
C:\Users\User\AppData\Local\Temp\ipykernel_18324\3220567389.py:2: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  y_test = np.array(y_test_feat)


#### One-hot encode y so that we can use it in ur training function

In [134]:
y_train = one_hot(y_train, num_classes = 10)
y_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], shape=(18900, 10))

In [135]:
y_val_oh = one_hot(y_val, num_classes = 10)
y_test_oh = one_hot(y_test, num_classes = 10)

#### Before i run the training code, i define the evaluation and testing code

In [137]:
# so now the evaluation and testing function defined
def evaluate_qnn(x, y_true, weights):
    # get the predictions from the qnn circuit
    preds = pnp.array([qnn(i, weights) for i in x])
    # convert the predictions from the [-1, 1] form to [0, 1] form
    preds = (preds + 1) / 2
    # generate the logits from the predictions
    logits = preds @ w_classical + b_classical
    # use soft max to geerate probabilities from the logits of the predictions
    # first we generate the exponential of the logits substractd from the maximum logit per row
    exp_logits = pnp.exp(logits - pnp.max(logits, axis = 1, keepdims = True))
    # generate the probabilities per row now
    probs = exp_logits / pnp.sum(exp_logits, axis = 1, keepdims = True)
    # so we get the highest probability and asign it a class then store the class in a variable y_pred
    y_pred = pnp.argmax(probs, axis = 1)
    # calculate the accuracy of the model
    accuracy = pnp.mean(y_pred == y_true)
    # return the accuracy
    return accuracy

In [138]:
###### so we want the training to be done in batches of 16 and for the training to  be done a 100 times
# so we import tqdm to help us keep track of time
from tqdm import tqdm
batch_size = 16
n_epochs = 100

#initialise a variable to be used to store the sum of the batch losses per epoch and the number of batches
sum_batch_loss = 0.0
num_batches = 0.0

# create a for loop to loop through each epoch
for epoch in range(n_epochs):
    # shuffle indices in the training data
    indices = np.random.permutation(len(x_train_encoded))
    # so now we want to loop through the training data in batches to do the training 
    for start in tqdm (range(0, len(x_train_encoded), batch_size), desc = f"Epoch {epoch + 1} / {n_epochs}"):
        batch_index = indices[start : start + batch_size]

        # now we use those shuffled indices we have gotten to select the x_train and y_train data to be used per batch
        x_batch = x_train_encoded[batch_index]
        y_batch = y_train[batch_index]

        # then the loss function takes in the weights, the batch of the x and y train and now learning begins
        weights = opt.step(lambda w_t: loss(w_t, x_batch, y_batch), weights)

        # now we calculate the loss per batch
        batch_loss = loss(weights, x_batch, y_batch)
        # then we add all the losses of each batch to get the loss of the whole epoch
        sum_batch_loss += batch_loss
        num_batches += 1

    # so here i will calculate the average batch loss
    avg_batch_loss = sum_batch_loss / num_batches
    # get the validation score of each epoch
    epoch_accuracy = evaluate_qnn(x_val_encoded, y_val, weights)

    # now print done when the epoch is done print done
    print(f"The training of Epoch {epoch + 1} is done ")
    print(f"The trainng loss at the end of {epoch + 1} is {avg_batch_loss:.4f}")
    print(f"The validation accuracy of {epoch + 1} is {epoch_accuracy:.4f}")

Epoch 1 / 100: 100%|██████████| 1182/1182 [25:19<00:00,  1.29s/it]


The training of Epoch 1 is done 
The trainng loss at the end of 1 is 2.3596
The validation accuracy of 1 is 0.1040


Epoch 2 / 100: 100%|██████████| 1182/1182 [25:43<00:00,  1.31s/it]


The training of Epoch 2 is done 
The trainng loss at the end of 2 is 2.3309
The validation accuracy of 2 is 0.0970


Epoch 3 / 100: 100%|██████████| 1182/1182 [11:42<00:00,  1.68it/s]


The training of Epoch 3 is done 
The trainng loss at the end of 3 is 2.3213
The validation accuracy of 3 is 0.0970


Epoch 4 / 100: 100%|██████████| 1182/1182 [25:33<00:00,  1.30s/it]


The training of Epoch 4 is done 
The trainng loss at the end of 4 is 2.3166
The validation accuracy of 4 is 0.1002


Epoch 5 / 100: 100%|██████████| 1182/1182 [25:11<00:00,  1.28s/it]


The training of Epoch 5 is done 
The trainng loss at the end of 5 is 2.3136
The validation accuracy of 5 is 0.1032


Epoch 6 / 100: 100%|██████████| 1182/1182 [48:49<00:00,  2.48s/it]   


The training of Epoch 6 is done 
The trainng loss at the end of 6 is 2.3113
The validation accuracy of 6 is 0.0921


Epoch 7 / 100: 100%|██████████| 1182/1182 [12:31<00:00,  1.57it/s]


The training of Epoch 7 is done 
The trainng loss at the end of 7 is 2.3093
The validation accuracy of 7 is 0.0951


Epoch 8 / 100: 100%|██████████| 1182/1182 [12:20<00:00,  1.60it/s]


The training of Epoch 8 is done 
The trainng loss at the end of 8 is 2.3078
The validation accuracy of 8 is 0.0941


Epoch 9 / 100: 100%|██████████| 1182/1182 [43:28<00:00,  2.21s/it]    


The training of Epoch 9 is done 
The trainng loss at the end of 9 is 2.3066
The validation accuracy of 9 is 0.0931


Epoch 10 / 100: 100%|██████████| 1182/1182 [11:35<00:00,  1.70it/s]


The training of Epoch 10 is done 
The trainng loss at the end of 10 is 2.3056
The validation accuracy of 10 is 0.0914


Epoch 11 / 100: 100%|██████████| 1182/1182 [11:24<00:00,  1.73it/s]


The training of Epoch 11 is done 
The trainng loss at the end of 11 is 2.3049
The validation accuracy of 11 is 0.0960


Epoch 12 / 100: 100%|██████████| 1182/1182 [15:13<00:00,  1.29it/s]  


The training of Epoch 12 is done 
The trainng loss at the end of 12 is 2.3042
The validation accuracy of 12 is 0.0911


Epoch 13 / 100: 100%|██████████| 1182/1182 [11:41<00:00,  1.68it/s]


The training of Epoch 13 is done 
The trainng loss at the end of 13 is 2.3037
The validation accuracy of 13 is 0.0909


Epoch 14 / 100: 100%|██████████| 1182/1182 [11:55<00:00,  1.65it/s]


The training of Epoch 14 is done 
The trainng loss at the end of 14 is 2.3032
The validation accuracy of 14 is 0.0926


Epoch 15 / 100: 100%|██████████| 1182/1182 [12:34<00:00,  1.57it/s]


The training of Epoch 15 is done 
The trainng loss at the end of 15 is 2.3028
The validation accuracy of 15 is 0.0983


Epoch 16 / 100: 100%|██████████| 1182/1182 [11:54<00:00,  1.65it/s]


The training of Epoch 16 is done 
The trainng loss at the end of 16 is 2.3024
The validation accuracy of 16 is 0.0980


Epoch 17 / 100: 100%|██████████| 1182/1182 [11:44<00:00,  1.68it/s]


The training of Epoch 17 is done 
The trainng loss at the end of 17 is 2.3021
The validation accuracy of 17 is 0.0970


Epoch 18 / 100: 100%|██████████| 1182/1182 [25:28<00:00,  1.29s/it]   


The training of Epoch 18 is done 
The trainng loss at the end of 18 is 2.3019
The validation accuracy of 18 is 0.1002


Epoch 19 / 100: 100%|██████████| 1182/1182 [11:28<00:00,  1.72it/s]


The training of Epoch 19 is done 
The trainng loss at the end of 19 is 2.3016
The validation accuracy of 19 is 0.0983


Epoch 20 / 100: 100%|██████████| 1182/1182 [12:19<00:00,  1.60it/s]


The training of Epoch 20 is done 
The trainng loss at the end of 20 is 2.3014
The validation accuracy of 20 is 0.0970


Epoch 21 / 100: 100%|██████████| 1182/1182 [12:03<00:00,  1.63it/s]


The training of Epoch 21 is done 
The trainng loss at the end of 21 is 2.3012
The validation accuracy of 21 is 0.0936


Epoch 22 / 100: 100%|██████████| 1182/1182 [12:01<00:00,  1.64it/s]


The training of Epoch 22 is done 
The trainng loss at the end of 22 is 2.3010
The validation accuracy of 22 is 0.0968


Epoch 23 / 100: 100%|██████████| 1182/1182 [12:03<00:00,  1.63it/s]


The training of Epoch 23 is done 
The trainng loss at the end of 23 is 2.3009
The validation accuracy of 23 is 0.0958


Epoch 24 / 100: 100%|██████████| 1182/1182 [11:31<00:00,  1.71it/s]


The training of Epoch 24 is done 
The trainng loss at the end of 24 is 2.3007
The validation accuracy of 24 is 0.0926


Epoch 25 / 100: 100%|██████████| 1182/1182 [11:44<00:00,  1.68it/s]


The training of Epoch 25 is done 
The trainng loss at the end of 25 is 2.3006
The validation accuracy of 25 is 0.0958


Epoch 26 / 100: 100%|██████████| 1182/1182 [12:04<00:00,  1.63it/s]


The training of Epoch 26 is done 
The trainng loss at the end of 26 is 2.3004
The validation accuracy of 26 is 0.0916


Epoch 27 / 100: 100%|██████████| 1182/1182 [11:59<00:00,  1.64it/s]


The training of Epoch 27 is done 
The trainng loss at the end of 27 is 2.3003
The validation accuracy of 27 is 0.0921


Epoch 28 / 100: 100%|██████████| 1182/1182 [12:01<00:00,  1.64it/s]


The training of Epoch 28 is done 
The trainng loss at the end of 28 is 2.3002
The validation accuracy of 28 is 0.0909


Epoch 29 / 100: 100%|██████████| 1182/1182 [12:02<00:00,  1.64it/s]


The training of Epoch 29 is done 
The trainng loss at the end of 29 is 2.3001
The validation accuracy of 29 is 0.0938


Epoch 30 / 100: 100%|██████████| 1182/1182 [12:02<00:00,  1.64it/s]


The training of Epoch 30 is done 
The trainng loss at the end of 30 is 2.3000
The validation accuracy of 30 is 0.0923


Epoch 31 / 100: 100%|██████████| 1182/1182 [18:02<00:00,  1.09it/s]


The training of Epoch 31 is done 
The trainng loss at the end of 31 is 2.2999
The validation accuracy of 31 is 0.0926


Epoch 32 / 100: 100%|██████████| 1182/1182 [25:53<00:00,  1.31s/it]


The training of Epoch 32 is done 
The trainng loss at the end of 32 is 2.2998
The validation accuracy of 32 is 0.0946


Epoch 33 / 100: 100%|██████████| 1182/1182 [25:50<00:00,  1.31s/it]


The training of Epoch 33 is done 
The trainng loss at the end of 33 is 2.2997
The validation accuracy of 33 is 0.0931


Epoch 34 / 100: 100%|██████████| 1182/1182 [13:30<00:00,  1.46it/s]


The training of Epoch 34 is done 
The trainng loss at the end of 34 is 2.2997
The validation accuracy of 34 is 0.0975


Epoch 35 / 100: 100%|██████████| 1182/1182 [12:05<00:00,  1.63it/s]


The training of Epoch 35 is done 
The trainng loss at the end of 35 is 2.2996
The validation accuracy of 35 is 0.0933


Epoch 36 / 100: 100%|██████████| 1182/1182 [12:08<00:00,  1.62it/s]


The training of Epoch 36 is done 
The trainng loss at the end of 36 is 2.2995
The validation accuracy of 36 is 0.0963


Epoch 37 / 100: 100%|██████████| 1182/1182 [12:10<00:00,  1.62it/s]


The training of Epoch 37 is done 
The trainng loss at the end of 37 is 2.2995
The validation accuracy of 37 is 0.0926


Epoch 38 / 100: 100%|██████████| 1182/1182 [12:09<00:00,  1.62it/s]


The training of Epoch 38 is done 
The trainng loss at the end of 38 is 2.2994
The validation accuracy of 38 is 0.0968


Epoch 39 / 100: 100%|██████████| 1182/1182 [17:14<00:00,  1.14it/s]


The training of Epoch 39 is done 
The trainng loss at the end of 39 is 2.2994
The validation accuracy of 39 is 0.0956


Epoch 40 / 100: 100%|██████████| 1182/1182 [25:17<00:00,  1.28s/it]


The training of Epoch 40 is done 
The trainng loss at the end of 40 is 2.2993
The validation accuracy of 40 is 0.0916


Epoch 41 / 100: 100%|██████████| 1182/1182 [24:48<00:00,  1.26s/it]


The training of Epoch 41 is done 
The trainng loss at the end of 41 is 2.2992
The validation accuracy of 41 is 0.0926


Epoch 42 / 100: 100%|██████████| 1182/1182 [24:09<00:00,  1.23s/it]


The training of Epoch 42 is done 
The trainng loss at the end of 42 is 2.2992
The validation accuracy of 42 is 0.0906


Epoch 43 / 100: 100%|██████████| 1182/1182 [24:41<00:00,  1.25s/it]


The training of Epoch 43 is done 
The trainng loss at the end of 43 is 2.2992
The validation accuracy of 43 is 0.0963


Epoch 44 / 100: 100%|██████████| 1182/1182 [33:06<00:00,  1.68s/it]   


The training of Epoch 44 is done 
The trainng loss at the end of 44 is 2.2991
The validation accuracy of 44 is 0.0960


Epoch 45 / 100: 100%|██████████| 1182/1182 [6:22:05<00:00, 19.40s/it]      


The training of Epoch 45 is done 
The trainng loss at the end of 45 is 2.2991
The validation accuracy of 45 is 0.0956


Epoch 46 / 100: 100%|██████████| 1182/1182 [12:40<00:00,  1.55it/s]


The training of Epoch 46 is done 
The trainng loss at the end of 46 is 2.2990
The validation accuracy of 46 is 0.0906


Epoch 47 / 100: 100%|██████████| 1182/1182 [13:53<00:00,  1.42it/s]


The training of Epoch 47 is done 
The trainng loss at the end of 47 is 2.2990
The validation accuracy of 47 is 0.0958


Epoch 48 / 100: 100%|██████████| 1182/1182 [13:29<00:00,  1.46it/s]


The training of Epoch 48 is done 
The trainng loss at the end of 48 is 2.2990
The validation accuracy of 48 is 0.1007


Epoch 49 / 100: 100%|██████████| 1182/1182 [14:03<00:00,  1.40it/s]


The training of Epoch 49 is done 
The trainng loss at the end of 49 is 2.2989
The validation accuracy of 49 is 0.0926


Epoch 50 / 100: 100%|██████████| 1182/1182 [12:19<00:00,  1.60it/s]


The training of Epoch 50 is done 
The trainng loss at the end of 50 is 2.2989
The validation accuracy of 50 is 0.0911


Epoch 51 / 100: 100%|██████████| 1182/1182 [11:52<00:00,  1.66it/s]


The training of Epoch 51 is done 
The trainng loss at the end of 51 is 2.2988
The validation accuracy of 51 is 0.0933


Epoch 52 / 100: 100%|██████████| 1182/1182 [12:00<00:00,  1.64it/s]


The training of Epoch 52 is done 
The trainng loss at the end of 52 is 2.2988
The validation accuracy of 52 is 0.0904


Epoch 53 / 100: 100%|██████████| 1182/1182 [11:54<00:00,  1.66it/s]


The training of Epoch 53 is done 
The trainng loss at the end of 53 is 2.2988
The validation accuracy of 53 is 0.0914


Epoch 54 / 100: 100%|██████████| 1182/1182 [1:03:33<00:00,  3.23s/it]   


The training of Epoch 54 is done 
The trainng loss at the end of 54 is 2.2987
The validation accuracy of 54 is 0.0988


Epoch 55 / 100: 100%|██████████| 1182/1182 [2:10:52<00:00,  6.64s/it]     


The training of Epoch 55 is done 
The trainng loss at the end of 55 is 2.2987
The validation accuracy of 55 is 0.0906


Epoch 56 / 100: 100%|██████████| 1182/1182 [11:18<00:00,  1.74it/s]


The training of Epoch 56 is done 
The trainng loss at the end of 56 is 2.2987
The validation accuracy of 56 is 0.0960


Epoch 57 / 100: 100%|██████████| 1182/1182 [11:51<00:00,  1.66it/s]


The training of Epoch 57 is done 
The trainng loss at the end of 57 is 2.2987
The validation accuracy of 57 is 0.0923


Epoch 58 / 100: 100%|██████████| 1182/1182 [11:58<00:00,  1.65it/s]


The training of Epoch 58 is done 
The trainng loss at the end of 58 is 2.2986
The validation accuracy of 58 is 0.0931


Epoch 59 / 100: 100%|██████████| 1182/1182 [11:31<00:00,  1.71it/s]


The training of Epoch 59 is done 
The trainng loss at the end of 59 is 2.2986
The validation accuracy of 59 is 0.0965


Epoch 60 / 100: 100%|██████████| 1182/1182 [11:59<00:00,  1.64it/s]


The training of Epoch 60 is done 
The trainng loss at the end of 60 is 2.2986
The validation accuracy of 60 is 0.0914


Epoch 61 / 100: 100%|██████████| 1182/1182 [11:58<00:00,  1.65it/s]


The training of Epoch 61 is done 
The trainng loss at the end of 61 is 2.2986
The validation accuracy of 61 is 0.0921


Epoch 62 / 100: 100%|██████████| 1182/1182 [12:00<00:00,  1.64it/s]


The training of Epoch 62 is done 
The trainng loss at the end of 62 is 2.2985
The validation accuracy of 62 is 0.0960


Epoch 63 / 100: 100%|██████████| 1182/1182 [12:16<00:00,  1.61it/s]


The training of Epoch 63 is done 
The trainng loss at the end of 63 is 2.2985
The validation accuracy of 63 is 0.0931


Epoch 64 / 100: 100%|██████████| 1182/1182 [12:04<00:00,  1.63it/s]


The training of Epoch 64 is done 
The trainng loss at the end of 64 is 2.2985
The validation accuracy of 64 is 0.0928


Epoch 65 / 100: 100%|██████████| 1182/1182 [11:32<00:00,  1.71it/s]


The training of Epoch 65 is done 
The trainng loss at the end of 65 is 2.2985
The validation accuracy of 65 is 0.0933


Epoch 66 / 100: 100%|██████████| 1182/1182 [11:38<00:00,  1.69it/s]


The training of Epoch 66 is done 
The trainng loss at the end of 66 is 2.2985
The validation accuracy of 66 is 0.0958


Epoch 67 / 100: 100%|██████████| 1182/1182 [11:25<00:00,  1.73it/s]


The training of Epoch 67 is done 
The trainng loss at the end of 67 is 2.2985
The validation accuracy of 67 is 0.0938


Epoch 68 / 100: 100%|██████████| 1182/1182 [11:10<00:00,  1.76it/s] 


The training of Epoch 68 is done 
The trainng loss at the end of 68 is 2.2984
The validation accuracy of 68 is 0.0951


Epoch 69 / 100: 100%|██████████| 1182/1182 [11:49<00:00,  1.67it/s]


The training of Epoch 69 is done 
The trainng loss at the end of 69 is 2.2984
The validation accuracy of 69 is 0.0914


Epoch 70 / 100: 100%|██████████| 1182/1182 [23:01<00:00,  1.17s/it]


The training of Epoch 70 is done 
The trainng loss at the end of 70 is 2.2984
The validation accuracy of 70 is 0.0983


Epoch 71 / 100: 100%|██████████| 1182/1182 [26:50<00:00,  1.36s/it]


The training of Epoch 71 is done 
The trainng loss at the end of 71 is 2.2984
The validation accuracy of 71 is 0.0926


Epoch 72 / 100: 100%|██████████| 1182/1182 [29:06<00:00,  1.48s/it]


The training of Epoch 72 is done 
The trainng loss at the end of 72 is 2.2984
The validation accuracy of 72 is 0.0941


Epoch 73 / 100: 100%|██████████| 1182/1182 [20:04<00:00,  1.02s/it]


The training of Epoch 73 is done 
The trainng loss at the end of 73 is 2.2984
The validation accuracy of 73 is 0.0914


Epoch 74 / 100: 100%|██████████| 1182/1182 [24:09:20<00:00, 73.57s/it]       


The training of Epoch 74 is done 
The trainng loss at the end of 74 is 2.2983
The validation accuracy of 74 is 0.0956


Epoch 75 / 100: 100%|██████████| 1182/1182 [13:52<00:00,  1.42it/s]


The training of Epoch 75 is done 
The trainng loss at the end of 75 is 2.2983
The validation accuracy of 75 is 0.0951


Epoch 76 / 100: 100%|██████████| 1182/1182 [14:51<00:00,  1.33it/s]


The training of Epoch 76 is done 
The trainng loss at the end of 76 is 2.2983
The validation accuracy of 76 is 0.0975


Epoch 77 / 100: 100%|██████████| 1182/1182 [15:01<00:00,  1.31it/s]


The training of Epoch 77 is done 
The trainng loss at the end of 77 is 2.2983
The validation accuracy of 77 is 0.0926


Epoch 78 / 100: 100%|██████████| 1182/1182 [18:21<00:00,  1.07it/s]


The training of Epoch 78 is done 
The trainng loss at the end of 78 is 2.2983
The validation accuracy of 78 is 0.0980


Epoch 79 / 100: 100%|██████████| 1182/1182 [27:13<00:00,  1.38s/it] 


The training of Epoch 79 is done 
The trainng loss at the end of 79 is 2.2983
The validation accuracy of 79 is 0.0948


Epoch 80 / 100: 100%|██████████| 1182/1182 [19:13<00:00,  1.02it/s]


The training of Epoch 80 is done 
The trainng loss at the end of 80 is 2.2983
The validation accuracy of 80 is 0.0946


Epoch 81 / 100: 100%|██████████| 1182/1182 [15:51<00:00,  1.24it/s]


The training of Epoch 81 is done 
The trainng loss at the end of 81 is 2.2982
The validation accuracy of 81 is 0.0909


Epoch 82 / 100: 100%|██████████| 1182/1182 [15:35<00:00,  1.26it/s]


The training of Epoch 82 is done 
The trainng loss at the end of 82 is 2.2982
The validation accuracy of 82 is 0.0980


Epoch 83 / 100: 100%|██████████| 1182/1182 [13:38<00:00,  1.44it/s]


The training of Epoch 83 is done 
The trainng loss at the end of 83 is 2.2982
The validation accuracy of 83 is 0.0963


Epoch 84 / 100: 100%|██████████| 1182/1182 [12:27<00:00,  1.58it/s]


The training of Epoch 84 is done 
The trainng loss at the end of 84 is 2.2982
The validation accuracy of 84 is 0.0948


Epoch 85 / 100: 100%|██████████| 1182/1182 [11:45<00:00,  1.67it/s]


The training of Epoch 85 is done 
The trainng loss at the end of 85 is 2.2982
The validation accuracy of 85 is 0.0936


Epoch 86 / 100: 100%|██████████| 1182/1182 [11:33<00:00,  1.70it/s]


The training of Epoch 86 is done 
The trainng loss at the end of 86 is 2.2982
The validation accuracy of 86 is 0.0943


Epoch 87 / 100: 100%|██████████| 1182/1182 [11:20<00:00,  1.74it/s]


The training of Epoch 87 is done 
The trainng loss at the end of 87 is 2.2982
The validation accuracy of 87 is 0.0911


Epoch 88 / 100: 100%|██████████| 1182/1182 [2:20:11<00:00,  7.12s/it]   


The training of Epoch 88 is done 
The trainng loss at the end of 88 is 2.2982
The validation accuracy of 88 is 0.0951


Epoch 89 / 100: 100%|██████████| 1182/1182 [37:37<00:00,  1.91s/it]   


The training of Epoch 89 is done 
The trainng loss at the end of 89 is 2.2982
The validation accuracy of 89 is 0.0928


Epoch 90 / 100: 100%|██████████| 1182/1182 [12:21<00:00,  1.59it/s]


The training of Epoch 90 is done 
The trainng loss at the end of 90 is 2.2982
The validation accuracy of 90 is 0.0923


Epoch 91 / 100: 100%|██████████| 1182/1182 [12:44<00:00,  1.55it/s]


The training of Epoch 91 is done 
The trainng loss at the end of 91 is 2.2981
The validation accuracy of 91 is 0.0965


Epoch 92 / 100: 100%|██████████| 1182/1182 [12:17<00:00,  1.60it/s]


The training of Epoch 92 is done 
The trainng loss at the end of 92 is 2.2981
The validation accuracy of 92 is 0.0980


Epoch 93 / 100: 100%|██████████| 1182/1182 [12:17<00:00,  1.60it/s]


The training of Epoch 93 is done 
The trainng loss at the end of 93 is 2.2981
The validation accuracy of 93 is 0.0963


Epoch 94 / 100: 100%|██████████| 1182/1182 [12:12<00:00,  1.61it/s]


The training of Epoch 94 is done 
The trainng loss at the end of 94 is 2.2981
The validation accuracy of 94 is 0.0906


Epoch 95 / 100: 100%|██████████| 1182/1182 [12:19<00:00,  1.60it/s]


The training of Epoch 95 is done 
The trainng loss at the end of 95 is 2.2981
The validation accuracy of 95 is 0.0921


Epoch 96 / 100: 100%|██████████| 1182/1182 [12:14<00:00,  1.61it/s]


The training of Epoch 96 is done 
The trainng loss at the end of 96 is 2.2981
The validation accuracy of 96 is 0.1025


Epoch 97 / 100: 100%|██████████| 1182/1182 [12:20<00:00,  1.60it/s]


The training of Epoch 97 is done 
The trainng loss at the end of 97 is 2.2981
The validation accuracy of 97 is 0.0965


Epoch 98 / 100: 100%|██████████| 1182/1182 [11:41<00:00,  1.68it/s]


The training of Epoch 98 is done 
The trainng loss at the end of 98 is 2.2981
The validation accuracy of 98 is 0.0951


Epoch 99 / 100: 100%|██████████| 1182/1182 [12:00<00:00,  1.64it/s]


The training of Epoch 99 is done 
The trainng loss at the end of 99 is 2.2981
The validation accuracy of 99 is 0.0943


Epoch 100 / 100: 100%|██████████| 1182/1182 [11:41<00:00,  1.68it/s]


The training of Epoch 100 is done 
The trainng loss at the end of 100 is 2.2981
The validation accuracy of 100 is 0.0916


## Let's build a 16 and 20 qubit QNN and see whether it will perform better than the 8 qubit QNN

### The 16 qubit QNN built now

#### First we define, our number of qubits, number of layers and create our randomised weights

In [142]:
n_qubits_16 = x_train_encoded_16.shape[1]
n_layers_16 = 2

# now we create the randomised weights here
weights_16 = np.random.randn(n_qubits_16, n_layers_16, 3)

#### Now we define the 16 qubit QNN circuit

In [144]:
# now we define the decorator and we use autograd interface differentiator
@qml.qnode(dev_16, interface = "autograd")

# now lets define the circuit


SyntaxError: incomplete input (424059397.py, line 4)